### ISSUE TITLE
Mapping of lessons to agenda

### ISSUE THREAD

**Issue by lillythomas** [SERVIR-Amazonia/Peru-tensorflow-training#3]
@oyupanqui and @mbecerra1 

Here is a mapping of lessons from the [training website](https://developmentseed.org/tensorflow-eo-training-2/docs/index.html) to the [agenda website](https://servir-amazonia.github.io/Peru-tensorflow-training/). 

## Day 1
Introduction to Machine Learning, Deep Learning and Artificial Intelligence: 
- https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson1a_Intro_ML_NN_DL.html

Introduction to Google Colab, Tensorflow 2.0 and Keras Library: 
- Colab: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson2a_Intro_to_Google_Colab.html
- Tensorflow 2.0 and Keras part 1: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson2b_Intro_TensorFlow_Keras.html
- Tensorflow 2.0 and Keras part 2: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson2c_Intro_TF2_Keras_TFDS_RadiantEarth.html

Overview of the building blocks (tensors) of TensorFlow (Tensors), main methods, functions and datasets:
- https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson3_Intro_tensors_functions_datasets.html

Integrating TensorFlow with Google Earth Engine and Google Cloud Platform:
- GEE: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson4a_GEE_PythonAPI_TensorFlow_Regression.html
- GCP: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson4b_Integrations_with_Google_Cloud_Platform.html

## Day 2

Building, compiling, and training a deep learning segmentation model to process datasets:
- Processing for segmentation: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson5a_prep_data_ML_segmentation.html
- Segmentation with conv net: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson5b_deeplearning_segmentation_UNet.html
- Segmentation with ViT: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson5c_segmentation_ViT.html

Advanced Techniques for Deep Learning, metrics evaluation, data augmentation, etc:
- Evaluating Semantic Segmentation Models: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson6a_evaluation.html
- Dealing with limited data for semantic segmentation: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson6b_dealing_with_limited_data.html

Testing different architecture and transfer learning with Convolutional Neural Networks:
- Comparing deep learning architectures for different computer vision tasks on satellite imagery: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson7a_comparing_architectures.html
- Comparing RNNs and Transformers for Imagery: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson7b_comparing_RNN_transformer_architectures.html
- Transfer learning, fine-tuning: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson7c_transfer_learning_hyperparam_opt.html

TensorFlow advanced applications with Deep Learning:
- TensorFlow advanced applications with deep learning object detection, time-series analysis: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson8_advanced_applications.html
- Regression: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson4a_GEE_PythonAPI_TensorFlow_Regression.html
- hyperparameter tuning: https://developmentseed.org/tensorflow-eo-training-2/docs/Lesson7c_transfer_learning_hyperparam_opt.html

## Day 3

For the buildathons, we will use content from day 1 and 2 respectively.

**Comment by oyupanqui** [comment]
Thanks @lillythomas ! I have added the links to the agenda
