### ISSUE TITLE
photos folder URL

### ISSUE THREAD

**Issue by apuzzi** [SERVIR-Amazonia/Peru-tensorflow-training#6]
Please update the photos folder URL in `photos.md` after moving this folder to the appropriate location. 
The folder currently lives in the Caribbean trainings folder ("Peru"): https://drive.google.com/drive/folders/1HPL_hac2O050P-1K7ewO00yvAybS26py
I believe the photos should be stored somewhere here: https://drive.google.com/drive/folders/1w0fRH2QaptnDLUAljaz4r1_ruDRJdgWN

**Comment by oyupanqui** [comment]
Done! Thanks Andrea
